### ISSUE TITLE
Modelo del dominio

### ISSUE THREAD

**Issue by AndrextA** [mmasias/mmasias#6]
Hoy en la clase de ingeniería de software nos dijiste sobre este proyecto que podríamos tomar en consideración para construir el nuestro. La cosa es que no encuentro el enlace por ningún lado. También dijiste que no le tome foto porque estaba subido, pero al parecer no sé buscar. ¿Podridas compartirlo por aquí, por favor?
![WhatsApp Image 2024-11-08 at 12 52 39_5d312acc](https://github.com/user-attachments/assets/feae5c81-4445-4ca3-8036-15a3d8e191ae)

**Comment by mmasias** [comment]
No sé si lo encontraste. Por si acaso, aquí te dejo el enlace al [proyecto AgrimManager](https://github.com/mmasias/mmasias/blob/main/pyAgrimManager.md)

**Comment by AndrextA** [comment]
Gracias!
